sdk/src/main/res/values/strings.xml

Linear Ticket: [MOB-22](https://linear.app/stytch/issue/MOB-22)
1. Update "Sign in with email" button to instead read "Continue with email"

Update button text to 'Continue with email'

---

.github/workflows/publish.yml
build.gradle
scripts/publish-module.gradle
scripts/publish-root.gradle
sdk/build.gradle
sdk/src/main/AndroidManifest.xml
sdk/src/main/java/com/stytch/sdk/StytchUI.kt
sdk/src/main/res/values/themes.xml
testapp/build.gradle
testapp/src/main/AndroidManifest.xml
testapp/src/main/res/values-night/themes.xml
testapp/src/main/res/values/themes.xml

Automatically deploys to Maven Central on creating a new GitHub release

Automatic Gradle Deployment

---

exampleapp/src/main/AndroidManifest.xml
exampleapp/src/main/res/xml/network_security_config.xml
sdk/src/main/java/com/stytch/sdk/MagicLinksImpl.kt
sdk/src/main/java/com/stytch/sdk/OTPImpl.kt
sdk/src/main/java/com/stytch/sdk/PasswordsImpl.kt
sdk/src/main/java/com/stytch/sdk/SessionsImpl.kt
sdk/src/main/java/com/stytch/sdk/StorageHelper.kt
sdk/src/main/java/com/stytch/sdk/StytchClient.kt
sdk/src/main/java/com/stytch/sdk/StytchDispatchers.kt
sdk/src/main/java/com/stytch/sdk/network/StytchApi.kt
sdk/src/main/java/com/stytch/sessions/SessionAutoUpdater.kt
sdk/src/main/java/com/stytch/sessions/SessionStorage.kt
sdk/src/test/java/com/stytch/sdk/MagicLinksImplTest.kt
sdk/src/test/java/com/stytch/sdk/MagicLinksTest.kt
sdk/src/test/java/com/stytch/sdk/OTPImplTest.kt
sdk/src/test/java/com/stytch/sdk/OTPTest.kt
sdk/src/test/java/com/stytch/sdk/PasswordsImplTest.kt
sdk/src/test/java/com/stytch/sdk/PasswordsTest.kt
sdk/src/test/java/com/stytch/sdk/SessionsImplTest.kt
sdk/src/test/java/com/stytch/sdk/SessionsTest.kt
sdk/src/test/java/com/stytch/sdk/StytchClientTest.kt
sdk/src/test/java/com/stytch/sdk/network/StytchApiTest.kt
sdk/src/test/java/com/stytch/sdk/sessions/SessionAutoUpdaterTest.kt
sdk/src/test/java/com/stytch/sdk/sessions/SessionStorageTest.kt

Linear Ticket: [SDK-615](https://linear.app/stytch/issue/SDK-615)
1. Injects dependencies into implementations instead of relying on global objects. This makes it easier to test.
2. Adds a whole slew of tests
3. Adds network security config to exampleapp for proxy debugging (SDK-622)
Previous test coverage:
New test coverage:

Feature/SDK-615 Prefer dependency injection and update tests

---

sdk/src/main/java/com/stytch/sdk/AuthenticationFactor.kt
sdk/src/main/java/com/stytch/sdk/UserAuthenticationFactor.kt
sdk/src/main/java/com/stytch/sdk/UserManagement.kt
sdk/src/main/java/com/stytch/sdk/UserManagementImpl.kt
sdk/src/main/java/com/stytch/sdk/network/StytchApi.kt
sdk/src/main/java/com/stytch/sdk/network/StytchApiService.kt
sdk/src/test/java/com/stytch/sdk/UserManagementImplTest.kt

Linear Ticket:
[SDK-653](https://linear.app/stytch/issue/SDK-653)
[SDK-654](https://linear.app/stytch/issue/SDK-654)
1. Adds missing deletion endpoints for user management
2. Aligns with iOS on a single `deleteFactor` endpoint with typed parameter
3. Updates tests

SDK-653 SDK-654 add missing factor deletion endpoints and simplify/align with iOS

---

sdk/src/main/java/com/stytch/sdk/network/StytchApi.kt
sdk/src/main/java/com/stytch/sdk/network/StytchRequests.kt
sdk/src/main/java/com/stytch/sdk/passwords/Passwords.kt
sdk/src/main/java/com/stytch/sdk/passwords/PasswordsImpl.kt
sdk/src/test/java/com/stytch/sdk/network/StytchApiServiceTests.kt
sdk/src/test/java/com/stytch/sdk/network/StytchApiTest.kt
sdk/src/test/java/com/stytch/sdk/passwords/PasswordsImplTest.kt
sdk/src/test/java/com/stytch/sdk/passwords/PasswordsTest.kt

Linear Ticket: [SDK-789](https://linear.app/stytch/issue/SDK-789)
1. Add password reset template ID parameters as required

SDK-789 - Add reset password template ID

---

consumerExampleApp/src/main/java/com/stytch/exampleapp/OAuthViewModel.kt
consumerExampleApp/src/main/java/com/stytch/exampleapp/ui/OAuthScreen.kt
consumerExampleApp/src/main/res/values/strings.xml
sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuth.kt
sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuthImpl.kt
sdk/src/test/java/com/stytch/sdk/consumer/oauth/OAuthImplTest.kt

Linear Ticket: [SDK-947 ](https://linear.app/stytch/issue/SDK-947 )
1. Adds apple as a third party OAuth provider
- Embarrassing that this was missed 😬

SDK-947 Add apple as a third party OAuth provider

---

sdk/build.gradle
sdk/src/main/java/com/stytch/sdk/b2b/discovery/Discovery.kt
sdk/src/main/java/com/stytch/sdk/b2b/passwords/Passwords.kt
sdk/src/main/java/com/stytch/sdk/common/DeeplinkHandledStatus.kt
sdk/src/main/java/com/stytch/sdk/common/DeeplinkResponse.kt

Linear Ticket: [SDK-980](https://linear.app/stytch/issue/SDK-980)
1. Use dokka_version instead of hardcoded
2. Add missing documentation
-

SDK-980 Add missing documentation

---

README.md
sdk/build.gradle
sdk/module.md
sdk/src/main/java/com/stytch/sdk/common/Constants.kt

Linear Ticket: [SDK-1051](https://linear.app/stytch/issue/SDK-1051)
1. Update all references to stytch-kotlin to stytch-android
-

Update stytch-kotlin naming to stytch-android

---

sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuth.kt
sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuthImpl.kt
sdk/src/test/java/com/stytch/sdk/consumer/oauth/OAuthImplTest.kt

Linear Ticket: [SDK-764](https://linear.app/stytch/issue/SDK-764)
1. Adds new OAuth providers
-

Add new OAuth providers

---

README.md
consumerExampleApp/src/main/java/com/stytch/exampleapp/OAuthViewModel.kt
consumerExampleApp/src/main/java/com/stytch/exampleapp/ui/OAuthScreen.kt
consumerExampleApp/src/main/res/values/strings.xml
sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
sdk/src/main/java/com/stytch/sdk/consumer/README.md
sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuth.kt
sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuthImpl.kt
sdk/src/main/java/com/stytch/sdk/consumer/oauth/README.md
sdk/src/test/java/com/stytch/sdk/consumer/oauth/OAuthImplTest.kt

Linear Ticket: [AUTH-1480](https://linear.app/stytch/issue/AUTH-1480)
1. Add Yahoo OAuth
-

[AUTH-1480] Yahoo OAuth

---

sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApiService.kt
sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponses.kt
sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt

Linear Ticket: [SDK-1126](https://linear.app/stytch/issue/SDK-1126)
1. Same commit as from UI branch, fortunately it was all self-contained 🎉 
-

Add bootstrap fetching to headless SDK

---

sdk/build.gradle
sdk/src/main/java/com/stytch/sdk/consumer/network/models/ResponseData.kt

Fix incorrect type in response data and bump version

---

sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
sdk/src/main/java/com/stytch/sdk/common/dfp/CaptchaProvider.kt
sdk/src/main/java/com/stytch/sdk/common/extensions/RequestExt.kt
sdk/src/main/java/com/stytch/sdk/common/network/StytchDFPInterceptor.kt
sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
sdk/src/test/java/com/stytch/sdk/common/extensions/RequestExtTest.kt
sdk/src/test/java/com/stytch/sdk/common/network/StytchDFPInterceptorTest.kt

Linear Ticket: [SDK-1178](https://linear.app/stytch/issue/SDK-1178)
1. Updates bootstrap data to use new dfpProtectedAuth type
2. Updates logic to correctly handle DISABLED, ENABLED, PASSIVE states
-

Update DFP to handle DISABLED/ENABLED/PASSIVE

---

consumerExampleApp/src/main/java/com/stytch/exampleapp/PasskeysViewModel.kt
consumerExampleApp/src/main/java/com/stytch/exampleapp/ui/PasskeysScreen.kt
consumerExampleApp/src/main/res/values/strings.xml
sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
sdk/src/main/java/com/stytch/sdk/consumer/Typealiases.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerRequests.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerResponses.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/models/ResponseData.kt
sdk/src/main/java/com/stytch/sdk/consumer/passkeys/Passkeys.kt
sdk/src/main/java/com/stytch/sdk/consumer/passkeys/PasskeysImpl.kt
sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
sdk/src/test/java/com/stytch/sdk/consumer/passkeys/PasskeysImplTest.kt

1. Adds update method
2. Adds workbench example
-

Add Update method for Passkeys

---

.github/workflows/codeql.yml
.github/workflows/publish.yml
.github/workflows/runOnGithub.yml
.github/workflows/uiTests.yml
.github/workflows/versionedDocs.yml
build.gradle
sdk/build.gradle
ui/build.gradle
ui/module.md
ui/proguard-rules.pro
ui/src/main/kotlin/com/stytch/sdk/ui/StytchAuthenticationApp.kt

Linear Ticket: [SDK-1348](https://linear.app/stytch/issue/SDK-1348)
1. Adds a workflow for running UI/instrumented tests
2. Updates existing workflows to contain the new placeholder
-

SDK-1348 Add a UI test workflow

---

b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/MainActivity.kt
b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/OTPViewModel.kt
b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/ui/AppScreen.kt
b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/ui/OTPScreen.kt
b2bExampleApp/src/main/res/values/strings.xml
sdk/src/main/java/com/stytch/sdk/b2b/B2BTokenType.kt
sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
sdk/src/main/java/com/stytch/sdk/b2b/Typealiases.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApiService.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponses.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/models/Enums.kt
sdk/src/main/java/com/stytch/sdk/b2b/otp/OTP.kt
sdk/src/main/java/com/stytch/sdk/b2b/otp/OTPImpl.kt
sdk/src/main/java/com/stytch/sdk/common/network/ApiService.kt
sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
sdk/src/test/java/com/stytch/sdk/b2b/otp/OTPImplTest.kt

Linear Ticket: [SDK-1465](https://linear.app/stytch/issue/SDK-1465)
1. Adds OTP client for B2B
-

SDK-1465 B2B OTP

---

sdk/build.gradle
sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt

Linear Ticket: [SDK-1557](https://linear.app/stytch/issue/SDK-1557)
1. Fixes field name for totpId and double check any other camelCase (instead of snake_case) field names
-

SDK-1557 Fix field name for totpId

---

b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/MainActivity.kt
b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/OAuthViewModel.kt
b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/ui/AppScreen.kt
b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/ui/OAuthScreen.kt
b2bExampleApp/src/main/res/values/strings.xml
sdk/build.gradle
sdk/src/main/java/com/stytch/sdk/b2b/B2BTokenType.kt
sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
sdk/src/main/java/com/stytch/sdk/b2b/Typealiases.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApiService.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponses.kt
sdk/src/main/java/com/stytch/sdk/b2b/oauth/OAuth.kt
sdk/src/main/java/com/stytch/sdk/b2b/oauth/OAuthImpl.kt
sdk/src/main/java/com/stytch/sdk/b2b/oauth/README.md
sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionStorage.kt
sdk/src/main/java/com/stytch/sdk/common/Constants.kt
sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuth.kt
sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
sdk/src/test/java/com/stytch/sdk/b2b/oauth/OAuthImplTest.kt

Linear Ticket: [SDK-1464](https://linear.app/stytch/issue/SDK-1464)
1. Adds the OAuth client to B2B
-

SDK-1464 B2B OAuth client

---

sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
sdk/src/main/java/com/stytch/sdk/b2b/rbac/RBAC.kt
sdk/src/main/java/com/stytch/sdk/b2b/rbac/RBACImpl.kt
sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
sdk/src/test/java/com/stytch/sdk/b2b/rbac/RBACImplTest.kt
sdk/src/test/java/com/stytch/sdk/common/network/models/CommonResponseDataTest.kt

Linear Ticket: [SDK-1468](https://linear.app/stytch/issue/SDK-1468)
1. Adds Roles to MemberSessionData
2. Adds RBACPolicy to Bootstrap response
3. Implements policy checking functionality
4. Adds RBAC client
-

SDK-1468 Add RBAC

---

consumerExampleApp/src/main/java/com/stytch/exampleapp/TOTPViewModel.kt
consumerExampleApp/src/main/java/com/stytch/exampleapp/ui/AppScreen.kt
consumerExampleApp/src/main/java/com/stytch/exampleapp/ui/TOTPScreen.kt
consumerExampleApp/src/main/res/values/strings.xml
sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
sdk/src/main/java/com/stytch/sdk/consumer/Typealiases.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerRequests.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerResponses.kt
sdk/src/main/java/com/stytch/sdk/consumer/network/models/ResponseData.kt
sdk/src/main/java/com/stytch/sdk/consumer/totp/README.md
sdk/src/main/java/com/stytch/sdk/consumer/totp/TOTP.kt
sdk/src/main/java/com/stytch/sdk/consumer/totp/TOTPImpl.kt
sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
sdk/src/test/java/com/stytch/sdk/consumer/totp/TOTPImplTest.kt

Linear Ticket: [SDK-1457](https://linear.app/stytch/issue/SDK-1457)
1. Adds TOTP client
-

SDK-1457 Add B2C TOTP support

---

sdk/build.gradle

Should fix outstanding bouncycastle vulns

Bump bouncycastle

---

build.gradle
sdk/build.gradle

Bump detekt

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
sdk/build.gradle

Should fix (at least):
* SDK-1688
* SDK-1690
* SDK-1694
* SDK-1695

Bump gradle to resolve some dependabot alerts

---

.github/workflows/dependency-submission.yml
b2bExampleApp/build.gradle
build.gradle
consumerExampleApp/build.gradle
gradle/wrapper/gradle-wrapper.properties
sdk/build.gradle

Linear Ticket: [SDK-1728](https://linear.app/stytch/issue/SDK-1728)
1. Uploads dependency scan graph for easier dependency vuln tracking
-

Add develocity scan upload

---

sdk/build.gradle
sdk/src/main/java/com/stytch/sdk/common/utils/DateHelpers.kt

Linear Ticket: [SDK-1831](https://linear.app/stytch/issue/SDK-1831)
1. Update the date formatter to do the CORRECT format in the CORRECT language
-

Fix timestamp for clientSentAt

---

README.md

1. Update README to include notes about placeholder variables
- Closes #189 and #190

Update README to explain that _all_ placeholders need to be present for workbench apps

---

sdk/src/main/assets/dfp.html
sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
sdk/src/main/java/com/stytch/sdk/common/EndpointOptions.kt
sdk/src/main/java/com/stytch/sdk/common/StytchClientOptions.kt
sdk/src/main/java/com/stytch/sdk/common/dfp/DFPProvider.kt
sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt

Linear Ticket: [AUTH-3810](https://linear.app/stytch/issue/AUTH-3810)
1. Configures webview DFP to use a custom domain
-

Configure webview DFP with DFPPA domain

---

b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/OrganizationViewModel.kt
sdk/src/main/java/com/stytch/sdk/b2b/organization/Organization.kt
sdk/src/test/java/com/stytch/sdk/b2b/organization/OrganizationImplTest.kt

Linear Ticket: [SDK-1977](https://linear.app/stytch/issue/SDK-1977)
1. Provides types for specific operands
2. Some linting of demo app viewmodel
3. Adds tests
- This should be closer to what JS SDK does

SDK-1977 Make SearchQueryOperands more explicit

---

source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/Typealiases.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApiService.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponses.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/scim/SCIM.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/scim/SCIMImpl.kt
source/sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
source/sdk/src/test/java/com/stytch/sdk/b2b/scim/SCIMImplTest.kt
workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/MainActivity.kt
workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/OAuthViewModel.kt
workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/SCIMViewModel.kt
workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/ui/AppScreen.kt
workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/ui/SCIMScreen.kt
workbench-apps/b2b-workbench/src/main/res/values/strings.xml

Linear Ticket: [SDK-1998](https://linear.app/stytch/issue/SDK-1998)
1. Add SCIM client to B2B
2. Add tests
3. Update B2B Workbench to test
-

SDK-1998 Add SCIM client

---

source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
source/sdk/src/main/java/com/stytch/sdk/common/DeeplinkTokenPair.kt
source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
tutorials/Deeplinks.md

Linear Ticket: [SDK-1985](https://linear.app/stytch/issue/SDK-1985)
1. Adds parseDeeplink method to clients and updates Deeplink README
-

Add parseDeepLink method to clients, update README

---

README.md

Linear Ticket: [SDK-2033](https://linear.app/stytch/issue/SDK-2033)
1. Update main README with information about the organization of the repository and notes about how to run the example/workbench apps
-

SDK-2033 Update README

---

source/sdk/build.gradle
source/sdk/src/androidTest/java/com/stytch/sdk/ui/robots/StytchAuthenticationAppRobot.kt
source/sdk/src/androidTest/java/com/stytch/sdk/ui/tests/StytchAuthenticationAppTest.kt
source/sdk/src/main/java/com/stytch/sdk/ui/StytchAuthenticationApp.kt
source/sdk/src/main/res/values/strings.xml

Linear Ticket: [SDK-2121](https://linear.app/stytch/issue/SDK-2121)
1. Remove "primary authentication factor" check from UI config, as it's not present in JS SDK
2. Bump version
-

SDK-2121 Remove primary authentication factor check

---

source/sdk/build.gradle
source/sdk/src/main/java/com/stytch/sdk/b2b/Typealiases.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApiService.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponses.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/otp/OTP.kt
source/sdk/src/main/java/com/stytch/sdk/b2b/otp/OTPImpl.kt
source/sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIError.kt
source/sdk/src/main/java/com/stytch/sdk/common/extensions/HttpExceptionExt.kt
source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
source/sdk/src/test/java/com/stytch/sdk/b2b/oauth/OAuthImplTest.kt
source/sdk/src/test/java/com/stytch/sdk/b2b/otp/OTPImplTest.kt
source/sdk/src/test/java/com/stytch/sdk/common/errors/StytchErrorTests.kt
source/sdk/src/test/java/com/stytch/sdk/consumer/biometrics/BiometricsImplTest.kt
source/sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
source/sdk/src/test/java/com/stytch/sdk/consumer/oauth/OAuthImplTest.kt
source/sdk/src/test/java/com/stytch/sdk/ui/screens/MainScreenViewModelTest.kt
workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/OTPViewModel.kt
workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/ui/OTPScreen.kt
workbench-apps/b2b-workbench/src/main/res/values/strings.xml

Linear Ticket:
[SDK-2217](https://linear.app/stytch/issue/SDK-2217)
[SDK-2218](https://linear.app/stytch/issue/SDK-2218)
1. Adds `statusCode` to `StytchAPIError` class
2. Adds Email OTP to B2B
3. Adds new methods to b2b workbench
4. Bumps version for publish
-

Release 0.30.0

---

source/sdk/src/main/java/com/stytch/sdk/ui/b2b/StytchB2BAuthenticationApp.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/B2BUIAction.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/domain/B2BUIStateMachine.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/DiscoveryScreen.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/EmailConfirmationScreen.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/utils/B2BUIViewModelFactory.kt

Those three basically-the-same email confirmation pages

Email confirmation pages

---

source/sdk/build.gradle
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/StytchB2BAuthenticationApp.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/components/ResendableOTP.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/ProductComponent.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/StytchB2BProduct.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/StytchB2BProductConfig.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/navigation/Route.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/EmailMethodSelectionScreen.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/EmailOTPEntryScreen.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/MFAEnrollmentSelection.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/MainScreen.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/SMSOTPEntryScreen.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseEffectiveAuthConfig.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseEmailOTPAuthenticate.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseEmailOTPDiscoveryAuthenticate.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseEmailOTPDiscoverySend.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseEmailOTPLoginOrSignup.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2b/utils/B2BUIViewModelFactory.kt
workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/UIWorkbenchActivity.kt

Linear Ticket: [SDK-2337](https://linear.app/stytch/issue/SDK-2337)
1. Adds Email OTP to B2B UI
-

SDK-2337 Add Email OTP to B2B UI

---

source/sdk/build.gradle.kts

Version bump

---

source/sdk/build.gradle.kts
source/sdk/consumer-rules.pro

1. Include porguard rules for consumers to prevent developers from having to add their own when building minified releases
-

Include consumer proguard configuration

---

source/sdk/build.gradle.kts

Missed a reference

---

.github/workflows/autopublish.yml
.github/workflows/publish.yml
build.gradle.kts
gradle/libs.versions.toml
source/sdk/build.gradle.kts

Dryrun runs locally, so lets try on CI again

---

source/sdk/src/main/java/com/stytch/sdk/ui/b2b/B2BAuthenticationActivity.kt
source/sdk/src/main/java/com/stytch/sdk/ui/b2c/AuthenticationActivity.kt

Linear Ticket: [SDK-2825](https://linear.app/stytch/issue/SDK-2825)
1. 
-

SDK-2825 Start logging bootstrap data along with ui config for both B2C and B2B UI

---

.github/workflows/dependency-submission.yml
build.gradle.kts

bump workflow

---

build.gradle.kts
source/sdk/build.gradle.kts

Final final
