- sdk/src/main/java/com/stytch/sdk/Stytch.kt
Linear Ticket: [MOB-27](https://linear.app/stytch/issue/MOB-27)
1. Verify uri host is valid while handling deep link, return false (invalid deeplink) if host does not match host passed to Stytch during configuration
> Verify uri host is correct when handling deep link

- .github/workflows/publish.yml
- sdk/build.gradle
There was a syntax/indentation issue in my workflow file that prevented GitHub Actions release integration from working. This fixes that, and updates the version to 0.4.1.
> Fix syntax issue in publish.yml

- README.md
- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/StytchApi.kt
Grace is removing the `user_created` parameter from the login_or_create endpoint response. I don't use this, however, I realized I still need to remove it from the response data structure for it to deserialize correctly. This PR makes that change and updates the patch version number.
> Remove user created from login or create response

- sdk/src/main/java/com/stytch/sdk/network/StytchApi.kt
Linear Ticket: [SDK-622](https://linear.app/stytch/issue/SDK-622)
1. Add a network interceptor to explicitly set the content-type to stop OkHttp from automatically adding a charset which was causing failed API responses
- https://github.com/square/okhttp/issues/3081
> Feature/SDK-622 Fix OkHttp charset issue

- sdk/src/main/java/com/stytch/sdk/Biometrics.kt
- sdk/src/test/java/com/stytch/sdk/BiometricsTest.kt
- sdk/src/test/java/com/stytch/sdk/network/StytchApiServiceTests.kt
Linear Ticket: [SDK-631](https://linear.app/stytch/issue/SDK-631)
1. Remove unused parameter classes from Biometrics (and associated tests)
2. Add tests for biometrics and usermanagement requests
- The unused parameter classes were created by me when I first started fleshing out the SDK endpoints before realizing that the relevant API calls were being made in code, and the developer would never interact with those endpoints directly.
> SDK-631 Add tests for Biometrics and UserManagement requests

- exampleapp/src/main/java/com/stytch/exampleapp/ui/BiometricsScreen.kt
- sdk/src/main/java/com/stytch/sdk/Biometrics.kt
- sdk/src/main/java/com/stytch/sdk/BiometricsImpl.kt
- sdk/src/main/java/com/stytch/sdk/BiometricsProvider.kt
- sdk/src/main/java/com/stytch/sdk/BiometricsProviderImpl.kt
- sdk/src/test/java/com/stytch/sdk/BiometricsImplTest.kt
Linear Ticket: [SDK-687](https://linear.app/stytch/issue/SDK-687)
1. Adds a check to areBiometricsAvailable method to determine if the SecretKey is still valid. If it's been invalidated, delete the existing registration and return a status of BIOMETRICS_REVOKED
2. Change secretKey to a getter instead of a onetime shot
3. Delete the secret key when deleting registrations
> Feature/SDK-687 Rotate SecretKey on invalidation

- exampleapp/src/main/java/com/stytch/exampleapp/HomeViewModel.kt
- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/DeeplinkHandledStatus.kt
- sdk/src/main/java/com/stytch/sdk/StytchClient.kt
- sdk/src/main/java/com/stytch/sdk/TokenType.kt
- sdk/src/main/java/com/stytch/sdk/network/StytchErrorType.kt
- sdk/src/test/java/com/stytch/sdk/StytchClientTest.kt
Linear Ticket: [SDK-754](https://linear.app/stytch/issue/SDK-754)
1. Update `handle()` method to return a (new) `DeeplinkHandledStatus` type
2. Return correct data class for password reset deeplinks
3. Update tests
- This is more in alignment with how iOS handles deeplinks
> SDK-754 Enable Password Reset deeplink handler

- pull_request_template.md
- sdk/src/test/java/com/stytch/sdk/network/StytchApiServiceTests.kt
- sdk/src/test/java/com/stytch/sdk/utils/RecordedRequestExtensions.kt
Linear Ticket: [SDK-749](https://linear.app/stytch/issue/SDK-749)
1. Update PR template
2. Reduce boilerplate code in `StytchApiServiceTests.kt`
3. Document why we're ignoring exceptions in these tests, and limit the exception to the intended ignored one, so any other exceptions are still surfaced
4. Add verifyGet/verifyDelete/verifyPost helpers to explicitly check request body parameters
> Feature/SDK-749 Request testing improvements

- exampleapp/src/main/java/com/stytch/exampleapp/OAuthViewModel.kt
1. Add the DeeplinkHandledStatus checker to OAuthViewModel
- @nicole-stytch found this bug when trying to set up the demo app. After adding in this new status class (in lieu of the raw result), this one instance in the example app missed getting updated. Whoops!
> Update OAuthViewModel with new DeeplinkHandledStatus support

- README.md
- consumerExampleApp/build.gradle
- pull_request_template.md
- sdk/src/main/java/com/stytch/sdk/b2b/README.md
- sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- sdk/src/main/java/com/stytch/sdk/b2b/magicLinks/README.md
- sdk/src/main/java/com/stytch/sdk/b2b/member/README.md
- sdk/src/main/java/com/stytch/sdk/b2b/organization/README.md
- sdk/src/main/java/com/stytch/sdk/b2b/sessions/README.md
- sdk/src/main/java/com/stytch/sdk/consumer/README.md
- sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- sdk/src/main/java/com/stytch/sdk/consumer/biometrics/README.md
- sdk/src/main/java/com/stytch/sdk/consumer/magicLinks/README.md
- sdk/src/main/java/com/stytch/sdk/consumer/oauth/README.md
- sdk/src/main/java/com/stytch/sdk/consumer/otp/README.md
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/README.md
- sdk/src/main/java/com/stytch/sdk/consumer/sessions/README.md
- sdk/src/main/java/com/stytch/sdk/consumer/userManagement/README.md
Linear Ticket: [SDK-781](https://linear.app/stytch/issue/SDK-781)
1. Removes unnecessary BuildConfig strings from consumer example app
2. Updates PR template to remind us to keep our documentation and tests updated
3. Updates the root README to account for newly added authentication products, the split between consumer/B2B, the increased API level, new required configuration steps, etc. Also adds nifty badges!
4. Adds Consumer/B2B and product-specific READMEs
Most of the product specific READMEs are pretty lightweight/inconsequential, but the additional information for things like OAuth and Biometrics are (IMO) best communicated in a README, and it'd be weird to not have them for the other products, so they're there.
> Feature/SDK-781 READMEs

- sdk/src/main/java/com/stytch/sdk/common/oauth/OAuthError.kt
Linear Ticket: [SDK-880](https://linear.app/stytch/issue/SDK-880)
1. Update the classname used for serializing/deserializing OAuthError classes
- This doesn't affect functionality and would work regardless, it's just nice to have this match the package name
> Fix package name for serializing/deserializing OAuthError classes

- sdk/src/main/java/com/stytch/sdk/b2b/B2BTokenType.kt
- sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- sdk/src/main/java/com/stytch/sdk/common/TokenType.kt
- sdk/src/main/java/com/stytch/sdk/consumer/ConsumerTokenType.kt
- sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- sdk/src/test/java/com/stytch/sdk/b2b/B2BTokenTypeTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/ConsumerTokenTypeTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
Linear Ticket: [SDK-919](https://linear.app/stytch/issue/SDK-919)
1. Add canHandle method to clients
2. Split out token types so each client type only returns for their supported tokens
3. Add/update tests
- This is a little bigger than the iOS implementation, because I chose to split out the unique token types between consumer and B2B, so that if a user tries to validate a consumer deep link with a B2B client, it returns as expected. This might be something you want to address in iOS (it's edge-casey, but figured I'd call it out).
> SDK-919 CanHandle

- sdk/src/main/java/com/stytch/sdk/consumer/Typealiases.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerResponses.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/models/ResponseData.kt
- sdk/src/main/java/com/stytch/sdk/consumer/oauth/GoogleOneTapImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuth.kt
- sdk/src/test/java/com/stytch/sdk/consumer/oauth/GoogleOneTapImplTest.kt
Linear Ticket: [SDK-941](https://linear.app/stytch/issue/SDK-941)
1. Add userCreated to native OAuth responses
> SDK-941 Add userCreated to native OAuth responses

- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/DiscoveryViewModel.kt
- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/SSOViewModel.kt
- sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- sdk/src/main/java/com/stytch/sdk/b2b/discovery/Discovery.kt
- sdk/src/main/java/com/stytch/sdk/b2b/discovery/DiscoveryImpl.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/Enums.kt
- sdk/src/main/java/com/stytch/sdk/common/network/ApiService.kt
- sdk/src/main/java/com/stytch/sdk/common/utils/EnumHelpers.kt
- sdk/src/test/java/com/stytch/sdk/b2b/discovery/DiscoveryImplTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/discovery/DiscoveryTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- sdk/src/test/java/com/stytch/sdk/utils/RecordedRequestExtensions.kt
Linear Ticket: No Ticket
1. Add missing createOrganization params
2. Add them to the organization response model, too
3. Update tests
-
> Add missing create org params; add params to organization response model

- consumerExampleApp/src/main/java/com/stytch/exampleapp/ui/BiometricsScreen.kt
- sdk/src/main/java/com/stytch/sdk/consumer/biometrics/BiometricAvailability.kt
- sdk/src/main/java/com/stytch/sdk/consumer/biometrics/BiometricsImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/biometrics/BiometricsProvider.kt
- sdk/src/main/java/com/stytch/sdk/consumer/biometrics/BiometricsProviderImpl.kt
- sdk/src/test/java/com/stytch/sdk/consumer/biometrics/BiometricsImplTest.kt
Linear Ticket: [SDK-1036](https://linear.app/stytch/issue/SDK-1036)
1. Condense the biometrics availability status into 4 statuses
-
> Condense and simplify biometric availability checks

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerRequests.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/Passwords.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/PasswordsImpl.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/passwords/PasswordsImplTest.kt
1. Adds resetBySession method to consumer StytchClient
-
> Add resetBySession method to consumer StytchClient

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- sdk/src/main/java/com/stytch/sdk/common/dfp/CaptchaProvider.kt
- sdk/src/main/java/com/stytch/sdk/common/network/StytchDFPInterceptor.kt
- sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
- sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
Linear Ticket: [SDK-1129](https://linear.app/stytch/issue/SDK-1129)
1. Adds the captcha flow to the DFP interceptor
2. Removes shortcircuit now that we're getting the DFP settings from bootstrap data
- Our plan to move API configuration after the bootstrap call wasn't workable, because the API needs to be configured _before_ making the bootstrap call (obviously!) So now configuration and _DFP_ configuration are split into two methods, and the second one creates a new APIService (if applicable) that can be conditionally used (otherwise it falls back to the non-DFP APIService)
> SDK-1129 Integrate reCAPTCHA

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/common/dfp/DFPProvider.kt
- sdk/src/main/java/com/stytch/sdk/common/extensions/ContextExt.kt
- sdk/src/main/java/com/stytch/sdk/common/extensions/RequestBodyExt.kt
- sdk/src/main/java/com/stytch/sdk/common/extensions/RequestExt.kt
- sdk/src/main/java/com/stytch/sdk/common/extensions/ResponseExt.kt
- sdk/src/main/java/com/stytch/sdk/common/network/StytchDFPInterceptor.kt
- sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- sdk/src/test/java/com/stytch/sdk/common/extensions/RequestBodyExtTest.kt
- sdk/src/test/java/com/stytch/sdk/common/extensions/RequestExtTest.kt
- sdk/src/test/java/com/stytch/sdk/common/extensions/ResponseExtTest.kt
- sdk/src/test/java/com/stytch/sdk/common/network/StytchDFPInterceptorTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
Linear Ticket: [SDK-1130](https://linear.app/stytch/issue/SDK-1130)
1. Adds unit tests for DFP/Captcha request modifications
2. Updates DeviceInfo to always return `Android` as the platform, instead of the codename (IDK why it was like this to begin with?)
3. Fixes some tests that were broken in earlier DFP work (oops)
- This does not have tests for the DFP or Captcha provider themselves, since it relies on Android stuff and would need to be run as instrumented tests, of which we don't have any yet
> DFP: Unit tests

- consumerExampleApp/src/main/java/com/stytch/exampleapp/PasswordsViewModel.kt
- consumerExampleApp/src/main/java/com/stytch/exampleapp/ui/PasswordsScreen.kt
- consumerExampleApp/src/main/res/values/strings.xml
- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerRequests.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/Passwords.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/PasswordsImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/README.md
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/passwords/PasswordsImplTest.kt
Linear Ticket: [SDK-1172](https://linear.app/stytch/issue/SDK-1172)
1. Adds sessionDurationMinutes to password resetBySession
-
> Add sessionDurationMinutes to passwordresetbysession

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
- sdk/src/main/java/com/stytch/sdk/consumer/Typealiases.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerResponses.kt
- sdk/src/main/java/com/stytch/sdk/consumer/otp/OTP.kt
- sdk/src/main/java/com/stytch/sdk/consumer/otp/OTPImpl.kt
- sdk/src/test/java/com/stytch/sdk/consumer/otp/OTPImplTest.kt
Linear Ticket: [SDK-1201](https://linear.app/stytch/issue/SDK-1201)
1. Updates OTP Send methods to return a new response type that includes `method_id` (it's literally the same response type as LoginOrCreate returns)
-
> SDK-1201 update otp send response

- sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- sdk/src/main/java/com/stytch/sdk/consumer/Typealiases.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerRequests.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerResponses.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/models/ResponseData.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passkeys/Passkeys.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passkeys/PasskeysImpl.kt
Linear Ticket: [SDK-1191](https://linear.app/stytch/issue/SDK-1191)
1. Add a new `Passkeys` interface to the `StytchClient`
2. Add data models for Passkeys requests + responses
3. Set up calls to the WebAuthn API
- As part of the lean MVP for Passkeys, we are reusing the WebAuthn API, instead of creating a new Passkeys API.
- TODOs are to be completed in [SDK-1190](https://linear.app/stytch/issue/SDK-1190)
> Passkeys client/endpoint setup

- sdk/src/main/java/com/stytch/sdk/consumer/passkeys/PasskeysImpl.kt
- sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/passkeys/PasskeysImplTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/passkeys/PasskeysTest.kt
Linear Ticket: [SDK-1197](https://linear.app/stytch/issue/SDK-1197)
1. Moves Android specific credential provider stuff to a provider class for easier testing (same as we do for Biometrics)
2. Adds tests for all of the Passkeys changes
-
> SDK-1197 Passkeys unit tests

- consumerExampleApp/src/main/java/com/stytch/exampleapp/App.kt
- consumerExampleApp/src/main/java/com/stytch/exampleapp/ui/AppScreen.kt
- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionStorage.kt
- sdk/src/main/java/com/stytch/sdk/common/EncryptionManager.kt
- sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- sdk/src/main/java/com/stytch/sdk/consumer/magicLinks/MagicLinksImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/otp/OTPImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passkeys/PasskeysImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/sessions/ConsumerSessionStorage.kt
- sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/magicLinks/MagicLinksImplTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/otp/OTPImplTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/passkeys/PasskeysImplTest.kt
Linear Ticket: [SDK-1296](https://linear.app/stytch/issue/SDK-1296)
1. Add a fallback to reset encryptedsharedpreferences when the key is borked. This happens when we test multiple different signed APKs and the key becomes unreadable. This shouldn't happen in consumer apps, but it's bugged me enough in development to do something about it.
2. Change the name "activeSessionExists" for clarity; we don't know if it's active, just if it's persisted!
3. On launch, if we have any persisted session identifiers, try to authenticate the session (without extending it!). If it's invalid, the normal handler will kick in and clear it out.
4. Add an (optional) callback to the configure method and expose a flow to report the initialization state, and call that once everything is bootstrapped, dfp-ed, …
> SDK-1296 Validate persistent sessions and add ability to report configuration status

- sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPISchemaError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIUnreachableError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchSDKError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchSDKUsageError.kt
Linear Ticket: [SDK-1307](https://linear.app/stytch/issue/SDK-1307)
1. Adds new error classes for future implementation
- These classes obviously aren't used yet, it just sets up the implementation/inheritance hierarchy. Implementation will take place in SDK-1329 and SDK-1311
> SDK-1307 Add new error classes

- sdk/src/main/java/com/stytch/sdk/common/DeeplinkHandledStatus.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchSDKError.kt
- sdk/src/main/java/com/stytch/sdk/common/extensions/HttpExceptionExt.kt
- sdk/src/main/java/com/stytch/sdk/common/extensions/ThrowableExt.kt
- sdk/src/main/java/com/stytch/sdk/common/network/SafeApiCall.kt
- sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
- sdk/src/test/java/com/stytch/sdk/common/extensions/HttpExceptionExtTest.kt
- sdk/src/test/java/com/stytch/sdk/common/extensions/ThrowableExtTest.kt
- sdk/src/test/java/com/stytch/sdk/common/network/SafeApiCallTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/sessions/ConsumerSessionStorageTest.kt
- sdk/src/test/java/com/stytch/sdk/utils/HttpExceptionUtils.kt
Linear Ticket: [SDK-1316](https://linear.app/stytch/issue/SDK-1316)
1. Make DeeplinkHandledStatus report only a subset of SDKErrors for better DX
2. Minor refactoring for easier testing
3. Add some missing tests
4. Remove out some unused biometric-specific errors. On Android and iOS we expose the same information in an availability object (or a simple boolean). RN will be updated to match
- Not really a lot in this PR, but that's a good thing, because the other errors are already being tested for in existing tests
> SDK-1316 Test new errors

- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/Util.kt
- consumerExampleApp/src/main/java/com/stytch/exampleapp/Util.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPISchemaError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIUnreachableError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchSDKError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchSDKUsageError.kt
- sdk/src/test/java/com/stytch/sdk/common/errors/StytchErrorTests.kt
- sdk/src/test/java/com/stytch/sdk/consumer/oauth/GoogleOneTapImplTest.kt
1. Dumb down StytchError to the basics
2. Anything that is specific to a type of error (exception, url, etc) is only included for that type
3. Update util functions in workbench apps to account for above changes
4. Add some tests for each error type to make sure we're passing the correct name, etc
-
> Error simplification and additional tests

- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/HomeViewModel.kt
- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/SSOViewModel.kt
- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/Util.kt
- consumerExampleApp/src/main/java/com/stytch/exampleapp/HomeViewModel.kt
- consumerExampleApp/src/main/java/com/stytch/exampleapp/OAuthViewModel.kt
- consumerExampleApp/src/main/java/com/stytch/exampleapp/Util.kt
- sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPISchemaError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIUnreachableError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchSDKError.kt
- sdk/src/main/java/com/stytch/sdk/common/errors/StytchSDKUsageError.kt
- sdk/src/main/java/com/stytch/sdk/common/extensions/HttpExceptionExt.kt
- sdk/src/main/java/com/stytch/sdk/common/extensions/ThrowableExt.kt
- sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- sdk/src/test/java/com/stytch/sdk/common/errors/StytchErrorTests.kt
- sdk/src/test/java/com/stytch/sdk/consumer/biometrics/BiometricsImplTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/oauth/GoogleOneTapImplTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/oauth/OAuthImplTest.kt
Linear Ticket: No ticket
1. Remove the unnecessary snake_case error name
2. change description to message
3. Add errorType for the snake_cased error_type returned for API errors
-
> Fix casing

- ui/src/main/kotlin/com/stytch/sdk/ui/StytchAuthenticationApp.kt
Linear Ticket: [SDK-1352](https://linear.app/stytch/issue/SDK-1352)
1. The voyager documentation is a little sparse on deeplinks, and what I _thought_ would work, well, didn't. This explicitly pushes the desired screen, if necessary.
-
> SDK-1352 Deeplink handling

- .github/workflows/uiTests.yml
- build.gradle
- sdk/build.gradle
- ui/build.gradle
- ui/module.md
- ui/proguard-rules.pro
Linear Ticket: [SDK-1117](https://linear.app/stytch/issue/SDK-1117)
1. Updates R8 since the UI module was having some problems (see: https://stackoverflow.com/a/76954759)
2. Configures UI module for publishing
3. Starts adding in some initial documentation tasks, since that's relevant for publishing, but the real documentation will come in SDK-1344
- Tested publishing to mavenLocal:
> SDK-1117 Configure publishing for UI module

- .github/workflows/publishHeadless.yml
- .github/workflows/publishUi.yml
Linear Ticket: [SDK-1117](https://linear.app/stytch/issue/SDK-1117)
1. Makes the publishing task manual/workflow_dispatch and creates separate workflows for publishing headless and UI SDKs
-
> SDK-1117 Create manually triggered, separate publish tasks for SDK and UI

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/common/EncryptionManager.kt
- sdk/src/main/java/com/stytch/sdk/common/extensions/ContextExt.kt
Linear Ticket: [SDK-1357](https://linear.app/stytch/issue/SDK-1357)
1. Catch InvalidKeyException and treat it as an unrecoverable key error (ie: clear preferences and recreate)
- This is a followup to the Tink upgrade which, unfortunately, did not work :(
> SDK-1357 Catch and retry keysetmanager creation for InvalidKeyException, too

- sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
Linear Ticket: [SDK-1414](https://linear.app/stytch/issue/SDK-1414)
1. Adds profilePictureUrl to Provider class
- Tested in demo app with GitHub login
> SDK-1414 Add profile_picture_url to Provider class

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/common/network/StytchDFPInterceptor.kt
- sdk/src/test/java/com/stytch/sdk/common/network/StytchDFPInterceptorTest.kt
Linear Ticket: [SDK-1449](https://linear.app/stytch/issue/SDK-1449)
1. Bumps Google reCAPTCHA version due to a new vulnerability
2. Fixes a bug when sending events with DFP enabled (the fix is to _not_ try to append DFP/CAPTCHA tokens to events)
-
> SDK-1449 Bump reCAPTCHA

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/common/dfp/ActivityProvider.kt
Linear Ticket: [SDK-1499](https://linear.app/stytch/issue/SDK-1499)
1. Don't null the activity reference _unless_ it matches the last resumed activity. Fixes a bug when an app presents multiple activities because of the differences in activity lifecycles (eg: killing an activity resumes the previous activity _before_ the last activity is fully destroyed)
- Tested in workbench
> SDK-1499 Fix multi-activity bug

- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/HomeViewModel.kt
- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/ui/MainScreen.kt
- b2bExampleApp/src/main/res/values/strings.xml
- sdk/src/main/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinks.kt
- sdk/src/main/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinksImpl.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApiService.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponses.kt
- sdk/src/test/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinksImplTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinksTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
Linear Ticket: [SDK-1459](https://linear.app/stytch/issue/SDK-1459)
1. Adds functionality and tests for B2B.MagicLinks.Email.Invite
2. Updates Workbench app to test functionality
- Also fixes wrong docs for discoverySend
> SDK-1459 Add B2B MagicLinks.Email.Invite support

- README.md
- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/consumer/README.md
- sdk/src/main/java/com/stytch/sdk/consumer/passkeys/README.md
Linear Ticket: [SDK-1500](https://linear.app/stytch/issue/SDK-1500)
1. Adds documentation for Passkeys
-
> SDK-1500 Document passkeys better

- sdk/src/main/java/com/stytch/sdk/b2b/events/EventsImpl.kt
- sdk/src/main/java/com/stytch/sdk/common/utils/DateHelpers.kt
- sdk/src/main/java/com/stytch/sdk/consumer/events/EventsImpl.kt
Linear Ticket: [SDK-1538 ](https://linear.app/stytch/issue/SDK-1538 )
1. Updates the date string we send to match what the db is expecting
-
> SDK-1538 Use correct date format for events client_sent_at

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/common/StorageHelper.kt
- sdk/src/main/java/com/stytch/sdk/common/network/StytchAuthHeaderInterceptor.kt
Linear Ticket: [SDK-1576](https://linear.app/stytch/issue/SDK-1576)
1. Add guardrail for a potentially empty string being returned for a session token in auth interceptor
2. Ensure that we never persist or return an empty string from the storage helper
3. Lint 
4. Version bump
-
> SDK-1576 Fix potentially persisting/retrieving empty strings

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/common/EncryptionManager.kt
Linear Ticket: [SDK-1585](https://linear.app/stytch/issue/SDK-1585)
1. Use SecureRandom instead of Random to generate cryptographically secure challenges for PKCE
-
> SDK-1585 Use SecureRandom instead of Random for PKCE code challenges

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/b2b/sso/SSOImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/oauth/ThirdPartyOAuthImpl.kt
Linear Ticket: [SDK-1588](https://linear.app/stytch/issue/SDK-1588)
1. Use cname if available for oauth and sso
-
> SDK-1588 Enable CNAME domains for OAuth and SSO

- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/SSOViewModel.kt
- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/ui/SSOScreen.kt
- b2bExampleApp/src/main/res/values/strings.xml
- sdk/src/main/java/com/stytch/sdk/b2b/Typealiases.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApiService.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponses.kt
- sdk/src/main/java/com/stytch/sdk/b2b/oauth/OAuthImpl.kt
- sdk/src/main/java/com/stytch/sdk/b2b/organization/OrganizationImpl.kt
- sdk/src/main/java/com/stytch/sdk/b2b/sso/SSO.kt
- sdk/src/main/java/com/stytch/sdk/b2b/sso/SSOImpl.kt
- sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/sso/SSOImplTest.kt
- sdk/src/test/java/com/stytch/sdk/utils/RecordedRequestExtensions.kt
Linear Ticket: [SDK-1463](https://linear.app/stytch/issue/SDK-1463)
1. Add SSO.getConnections
2. Add SSO.deleteConnection
3. Add SSO.saml.createConnection
4. Add SSO.saml.updateConnection
5. Add SSO.saml.updateConnectionByURL
6. Add SSO.saml.deleteVerificationCertificate
7. Add SSO.oidc.createConnection
8. Add SSO.oidc.updateConnection
9. Fix oauth token test, now that B2B Oauth is supported
10. Fix typo in response data (`organizatioName` -> `organizationName`)
11. Fix potentially null refreshToken in B2B OAuth response
12. Fix a few instances of incorrect dispatcher use (was processing data on UI instead of IO dispatcher)
13. Update workbench with all new methods, and verify functionality
-
> SDK-1463 Add SSO Methods

- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/HomeViewModel.kt
- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/ui/MainScreen.kt
- b2bExampleApp/src/main/res/values/strings.xml
- sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- sdk/src/main/java/com/stytch/sdk/b2b/Typealiases.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApiService.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponses.kt
- sdk/src/main/java/com/stytch/sdk/b2b/searchManager/SearchManager.kt
- sdk/src/main/java/com/stytch/sdk/b2b/searchManager/SearchManagerImpl.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/searchManager/SearchManagerImplTest.kt
Linear Ticket: [SDK-1548](https://linear.app/stytch/issue/SDK-1548)
1. Adds searchOrganization (by slug) and searchMember (by email and orgId) methods
2. Updates workbench to test them
-
> SDK-1548 add search organizations and members functionality

- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
- sdk/src/main/java/com/stytch/sdk/consumer/oauth/GoogleOneTapImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/userManagement/UserAuthenticationFactor.kt
- sdk/src/main/java/com/stytch/sdk/consumer/userManagement/UserManagementImpl.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/userManagement/UserManagementImplTest.kt
Linear Ticket: [SDK-1548](https://linear.app/stytch/issue/SDK-1548)
1. Adds missing deleteFactor methods for TOTP and OAuth registrations
2. Adds some missing tests for webauthn and crypto deletes
-
> SDK-1548 Add missing B2C user methods

- consumerExampleApp/src/main/java/com/stytch/exampleapp/PasswordsViewModel.kt
- consumerExampleApp/src/main/java/com/stytch/exampleapp/ui/PasswordsScreen.kt
- consumerExampleApp/src/main/res/values/strings.xml
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
- sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerRequests.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/Passwords.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/PasswordsImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/README.md
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
- sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/passwords/PasswordsImplTest.kt
Linear Ticket: [SDK-1455](https://linear.app/stytch/issue/SDK-1455)
1. Adds reset password by existing password method
-
> SDK-1455 Add B2C Password Reset By Existing

- .github/workflows/versionedDocs.yml
Linear Ticket: [SDK-1558](https://linear.app/stytch/issue/SDK-1558)
1. Just two small changes to account for using multi-module dokka instead of versioned docs
- This gets us documentation for both Headless and UI (multi-module) but we lose the versioning support. Older versions (0.18.1 and older) can still be accessed at https://stytchauth.github.io/stytch-android/older/[VERSION]/index.html, but going forward, the docs will only be for the latest versions
> SDK-1558 fix docs workflow

- ui/src/main/kotlin/com/stytch/sdk/ui/data/EventTypes.kt
- ui/src/main/kotlin/com/stytch/sdk/ui/screens/EMLConfirmationScreenViewModel.kt
- ui/src/main/kotlin/com/stytch/sdk/ui/screens/MainScreenViewModel.kt
- ui/src/main/kotlin/com/stytch/sdk/ui/screens/NewUserScreenViewModel.kt
- ui/src/main/kotlin/com/stytch/sdk/ui/screens/OTPConfirmationScreenViewModel.kt
- ui/src/main/kotlin/com/stytch/sdk/ui/screens/PasswordResetSentScreenViewModel.kt
- ui/src/main/kotlin/com/stytch/sdk/ui/screens/ReturningUserScreenViewModel.kt
- ui/src/test/kotlin/com/stytch/sdk/ui/screens/EMLConfirmationScreenViewModelTest.kt
- ui/src/test/kotlin/com/stytch/sdk/ui/screens/MainScreenViewModelTest.kt
- ui/src/test/kotlin/com/stytch/sdk/ui/screens/NewUserScreenViewModelTest.kt
- ui/src/test/kotlin/com/stytch/sdk/ui/screens/OTPConfirmationScreenViewModelTest.kt
- ui/src/test/kotlin/com/stytch/sdk/ui/screens/PasswordResetSentScreenViewModelTest.kt
- ui/src/test/kotlin/com/stytch/sdk/ui/screens/ReturningUserScreenViewModelTest.kt
Linear Ticket: [SDK-1402](https://linear.app/stytch/issue/SDK-1402)
1. Adds missing event logging to mimic JS SDK
-
> SDK-1402 Add missing UI event logging

- .github/workflows/uiTests.yml
Linear Ticket: [SDK-1613](https://linear.app/stytch/issue/SDK-1613)
1. Removes AVD caching, because that was causing issues previously
2. Switch to ubuntu runner, as that's now the recommended runner
- Not only do the tests run now, they run much faster! Woohoo!
> SDK-1613 Fix uiTest runner

- b2bExampleApp/build.gradle
- build.gradle
- consumerExampleApp/build.gradle
A handful of the reported vulns are required by and still present in the latest Gradle version. Add some constraints to force using the fixed versions.
Also, don't minify debug builds anymore, that was just for testing.
> Add some constraints for gradle plugins that aren't updated with fixes yet

- sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionStorage.kt
- sdk/src/main/java/com/stytch/sdk/common/Constants.kt
- sdk/src/main/java/com/stytch/sdk/common/StorageHelper.kt
- sdk/src/test/java/com/stytch/sdk/b2b/sessions/B2BSessionStorageTest.kt
Linear Ticket: [SDK-1716](https://linear.app/stytch/issue/SDK-1716)
1. Add a persisted expiration timestamp for ISTs and enforce that we don't persist/use ISTs after the 10 minute expiration
- This is (basically) the same fix we did for RN. @nidal-stytch this is what I mentioned we'd need to do in iOS, too, when we get to SDK-1526
> Handle IST 10 minute expiration

- sdk/build.gradle
- sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessions.kt
- sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionsImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/sessions/Sessions.kt
- sdk/src/main/java/com/stytch/sdk/consumer/sessions/SessionsImpl.kt
Linear Ticket: [SDK-1727](https://linear.app/stytch/issue/SDK-1727)
1. Requires a non-null session token and JWT to manually update/hydrate a session
-
> SDK-1727 require non null session token and session jwt in updatesession

- .github/workflows/dependency-submission.yml
- build.gradle
- sdk/build.gradle
- ui/build.gradle
Verified that _these_ changes will officially close out all remaining dependabot issues by (temporarily) switching the GH default branch and force running the dependency submission action
> More dependency updates

- sdk/src/main/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinksImpl.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
- sdk/src/main/java/com/stytch/sdk/b2b/oauth/OAuthImpl.kt
- sdk/src/main/java/com/stytch/sdk/b2b/passwords/PasswordsImpl.kt
- sdk/src/main/java/com/stytch/sdk/b2b/sso/SSOImpl.kt
- sdk/src/main/java/com/stytch/sdk/common/StorageHelper.kt
- sdk/src/main/java/com/stytch/sdk/consumer/magicLinks/MagicLinksImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuthImpl.kt
- sdk/src/main/java/com/stytch/sdk/consumer/passwords/PasswordsImpl.kt
- sdk/src/test/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinksImplTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/oauth/OAuthImplTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/passwords/PasswordsImplTest.kt
- sdk/src/test/java/com/stytch/sdk/b2b/sso/SSOImplTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/magicLinks/MagicLinksImplTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/oauth/OAuthImplTest.kt
- sdk/src/test/java/com/stytch/sdk/consumer/passwords/PasswordsImplTest.kt
[SDK-1825](https://linear.app/stytch/issue/SDK-1825)
[SDK-1828](https://linear.app/stytch/issue/SDK-1828)
1. Clear the local PKCE values every time they are used to prevent storing/retrieving outdated tokens, or passing them to endpoints that don't expect them (ie: B2B magic links authenticate during an invite flow)
2. Make the PKCE code verifier optional for B2B magic links authenticate
-
> SDK-1825 SDK-1828 PKCE lifecycle fixes

- ui/src/androidTest/kotlin/com/stytch/sdk/ui/data/StytchUIConfigTypes.kt
- ui/src/main/kotlin/com/stytch/sdk/ui/screens/NewUserScreen.kt
Linear Ticket: [SDK-1490](https://linear.app/stytch/issue/SDK-1490)
1. Only show password creation options on new user screen if passwords are enabled
-
> Only show password creation on new user screen if passwords are enabled

- build.gradle
- sdk/build.gradle
- ui/build.gradle
Linear Ticket: [SDK-1834](https://linear.app/stytch/issue/SDK-1834)
1. Don't force jackson BOM upgrade, rely on just the woodstox version resolution to hopefully avoid dependabot issues
-
> SDK-1834 Fix Dokka issues

- .github/workflows/versionedDocs.yml
1. Stop trying to generate versioned docs since we only expose latest version docs
- Since the introduction of the UI SDK, we've stopped supporting versioned docs, as Dokka multi module + versioning doesn't seem to be supported. We decided to just live with latest-version docs, but never updated the workflow. This was fine, but costly, as we were running doc generation for versions that were never going to be exposed. However, v0.25.0 introduced some changes that _broke_ dokka generation (and have since been fixed), but that meant that attempting to generate versioned docs failed for that version and, thus, failed to generate _any_ docs. So, this codifies that we are only doing latest version docs, gets our doc publishing working again, and maybe saves a little money on runners.
> Stop wasting time on versioned docs

- sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- sdk/src/main/java/com/stytch/sdk/common/EndpointOptions.kt
- sdk/src/main/java/com/stytch/sdk/common/StytchClientOptions.kt
- sdk/src/main/java/com/stytch/sdk/common/dfp/DFPProvider.kt
- sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
Linear Ticket: [AUTH-3810](https://linear.app/stytch/issue/AUTH-3810)
1. Configures native DFP to use a custom domain
- This is the same as #199, just for native DFP
> Configure native DFP with DFPPA domain

- b2bExampleApp/src/main/java/com/stytch/exampleapp/b2b/OAuthViewModel.kt
- sdk/src/main/java/com/stytch/sdk/b2b/oauth/OAuthImpl.kt
- sdk/src/main/java/com/stytch/sdk/common/utils/URIHelpers.kt
- sdk/src/main/java/com/stytch/sdk/consumer/oauth/OAuth.kt
- sdk/src/main/java/com/stytch/sdk/consumer/oauth/ThirdPartyOAuthImpl.kt
Linear Ticket: [SDK-1996](https://linear.app/stytch/issue/SDK-1996)
1. Extract buildUri function for reuse between B2B and consumer
2. Correctly encode list and map types
-
> SDK-1996 Fix crashing when encoding list and map types in oauth start URLs

- source/sdk/src/main/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinks.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinksImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BRequests.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/oauth/OAuth.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/otp/OTP.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/passwords/Passwords.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/passwords/PasswordsImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessions.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sso/SSO.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sso/SSOImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/ApiService.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/models/CommonRequests.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/magicLinks/MagicLinks.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/magicLinks/MagicLinksImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerRequests.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/otp/OTP.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/otp/OTPImpl.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinksImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/passwords/PasswordsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/magicLinks/MagicLinksImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/otp/OTPImplTest.kt
Linear Ticket: [SDK-1911](https://linear.app/stytch/issue/SDK-1911)
1. Adds a Locale enum and updates the (few) existing usages to use it
2. Adds locale param to all supported endpoints
-
> SDK-1911 Add Locale to supported endpoints

- source/sdk/src/main/java/com/stytch/sdk/b2b/scim/SCIM.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/scim/SCIMImpl.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/scim/SCIMImplTest.kt
- workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/SCIMViewModel.kt
No ticket.
1. Removes unnecessary `connectionId` parameter from `SCIM.getConnection` methods
-
> Remove unnecessary parameter from SCIM.getConnection methods

- source/sdk/build.gradle
- source/sdk/src/main/java/com/stytch/sdk/consumer/magicLinks/MagicLinksImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerRequests.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/magicLinks/MagicLinksImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
Linear Ticket: No Ticket
1. Looks like we've never been passing the signup magic link URL for consumer EML loginOrCreate 😬 
-
> Add missing signup magic link url to consumer EML loginOrCreate

- .github/workflows/autopublish.yml
- .github/workflows/publish.yml
- source/sdk/build.gradle
Linear Ticket: [SDK-2057](https://linear.app/stytch/issue/SDK-2057)
1. Creates an autopublish workflow to avoid instances where we forget to publish a release 😬 
- The checking of existing tags and conditional kick off of jobs definitely works, but the two pieces that are _untested_ are the actual publishing workflow (it reuses the existing one, so it _should_ be fine, but VSCode is complaining it can't find the action? It should work though, based on the ones we have in our other repos...) and the tag/release creation (those are both fairly straightforward, but I didn't want to pollute the repo with testing tags/versions)
> Setup autopublish workflow

- source/sdk/build.gradle
- source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/Enums.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/oauth/OAuth.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/oauth/OAuthImpl.kt
Linear Ticket:
[SDK-2038](https://linear.app/stytch/issue/SDK-2038)
[SDK-2041](https://linear.app/stytch/issue/SDK-2041)
[SDK-2042](https://linear.app/stytch/issue/SDK-2042)
1. Adds Github, Hubspot, and Slack as supported B2B OAuth providers
2. Adds new B2BAuthenticationFactors instead of reusing the consumer ones, which aren't all relevant
3. Bumps version
-
> Add missing B2B OAuth Providers

- .github/workflows/autopublish.yml
- .github/workflows/versionedDocs.yml
Linear Ticket: [SDK-2103](https://linear.app/stytch/issue/SDK-2103)
1. Docs workflow was using mismatched versions of the artifact upload and download steps, causing it to fail
2. Local git wasn't configured with a name/email, so tag creation failed
3. I _think_ the release publish was actually just a flake from the Maven server, as a subsequent publish succeeded manually
-
> Fix GH workflows

- source/sdk/build.gradle
- source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- source/sdk/src/main/java/com/stytch/sdk/common/StytchLazyDelegate.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
Linear Ticket: [SDK-2111](https://linear.app/stytch/issue/SDK-2111)
1. By exposing flows that read the values from shared preferences, we exposed a (harmless, but frustrating when offline) race condition for reporting authentication state. This change maintains our initialization assertion while ensuring that no shared preferences access attempts are made before full initialization
-
> Move to lazy delegates with custom getter to avoid race conditions with SharedPreferences

- source/sdk/src/main/AndroidManifest.xml
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/StytchB2BAuthenticationApp.kt
- workbench-apps/b2b-workbench/build.gradle
- workbench-apps/b2b-workbench/src/main/AndroidManifest.xml
- workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/HeadlessWorkbenchActivity.kt
- workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/MainActivity.kt
- workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/UIWorkbenchActivity.kt
Linear Ticket: [SDK-2256](https://linear.app/stytch/issue/SDK-2256)
1. Add B2B activity to SDK manifest (so it can actually launch!)
2. Change B2B Workbench start activity to one that allows you to switch between headless and UI testing
3. Create a blank UI testing activity to validate that it launches correctly
-
> Update B2B Workbench app to support both headless and B2B UI testing

- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/StytchB2BAuthenticationApp.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/domain/MFAReducers.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/DiscoveryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/MFAEnrollmentSelection.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/PasswordForgotScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/RecoveryCodesEntryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/RecoveryCodesSaveScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/SMSOTPEnrollmentScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/SMSOTPEntryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/TOTPEnrollmentScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/TOTPEntryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/utils/B2BUIViewModelFactory.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/shared/components/StytchButton.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/shared/components/StytchTextButton.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/shared/data/PhoneNumberState.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/shared/utils/PhoneNumberVisualTransformation.kt
Linear Ticket: 
[SDK-2248](https://linear.app/stytch/issue/SDK-2248)
[SDK-2249](https://linear.app/stytch/issue/SDK-2249)
[SDK-2250](https://linear.app/stytch/issue/SDK-2250)
[SDK-2251](https://linear.app/stytch/issue/SDK-2251)
1. Adds RecoveryCodesSaveScreen, RecoveryCodesEntryScreen, SMSOTPEnrollmentScreen, SMSOTPEntryScreen
2. Parses the phone number from the API into our PhoneNumberState format when encountering an already enrolled MFA flow
3. Adds some helpers for extracting/formatting phone numbers
-
> Add final MFA screens

- source/sdk/build.gradle
- source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionStorage.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/sessions/ConsumerSessionStorage.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/member/MemberImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/organization/OrganizationImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/otp/OTPImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/recoveryCodes/RecoveryCodesImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/sessions/B2BSessionStorageTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/totp/TOTPImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/sessions/ConsumerSessionStorageTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/sessions/SessionStorageTest.kt
Linear Ticket: [SDK-2311](https://linear.app/stytch/issue/SDK-2311)
1. Moves the declaration of the flows to the top of the file, on the off-chance that _somehow_ a value is being set (and trying to emit) before the flow has been created? Since [Kotlin classes are created top-to-bottom](https://discuss.kotlinlang.org/t/property-declaration-order-in-file-shouldnt-matter/3872), the "source" properties _were_ being created before the flows. I'm unsure how the source property _setters_ would be called before the flows were created, though.
2. Initializes the flows with a `null` value and then emits the desired value in the new-at-the-bottom `init` method? This goes along with the above. If I move the property initializers above the "source" properties, I don't want the source property …
> Attempt to address reported NPE on startup

- source/sdk/build.gradle
- source/sdk/src/main/java/com/stytch/sdk/common/dfp/ActivityProvider.kt
1. We only actually need to set the current activity in onResumed, as that's the last state when an activity is visible
2. We don't need to explicitly null out the weakreference, as this class is scoped to the lifetime of the application, and it's very difficult to accurately know the exact order that the lifecycle events will fire when launching multiple activities. The previous implementation worked when launching between different activities, but failed when you launched the same activity back-to-back. This solution works in both cases, plus navigating back to an existing activity.
-
> Be less aggressive when nulling out the current activity; bump version

- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/DeepLinkParserScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/DiscoveryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/MainScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/PasswordResetScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/SMSOTPEntryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseDiscoveryIntermediateSessionExchange.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseMagicLinksAuthenticate.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseMagicLinksDiscoverySend.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseOAuthAuthenticate.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseOTPSMSAuthenticate.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UsePasswordResetByEmail.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/utils/B2BUIViewModelFactory.kt
1. There were some places where we were not passing the provided session duration minutes to the appropriate authenticate calls. This fixes that.
-
> Ensure we pass session duration minutes to all authenticate calls

- source/sdk/build.gradle
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/B2BAuthenticationViewModel.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/BaseViewModel.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/StytchB2BAuthenticationApp.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/B2BUIAction.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/B2BUIState.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/domain/B2BUIStateMachine.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/DeepLinkParserScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/DiscoveryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/MainScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/PasswordResetScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/SMSOTPEntryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseDiscoveryIntermediateSessionExchange.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseMagicLinksAuthenticate.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseMagicLinksDiscoverySend.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseOAuthAuthenticate.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseOTPSMSAuthenticate.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UsePasswordResetByEmail.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/utils/B2BUIViewModelFactory.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/shared/components/FormFieldStatus.kt
1. GenericErrorMessage was being used for JIT errors, but never surfaced. Since we are only using the error message from the StytchError, unify the two into a single setter/source of truth, so all will be displayed as expected
2. Increase the timeout of the error autodismissal from 3 seconds to 5 seconds
3. #241 
-
> B2B UI - Post launch bugfixes/improvements

- source/sdk/build.gradle
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/screens/MainScreenViewModel.kt
- source/sdk/src/test/java/com/stytch/sdk/ui/b2c/screens/MainScreenViewModelTest.kt
Linear Ticket: [SDK-2348](https://linear.app/stytch/issue/SDK-2348)
1. If passwords are not enabled in the dashboard, we were failing when calling the user search. This change is to ONLY make the user search if passwords are a configured option. Without this change, if a developer had passwords disabled in their dashboard, and only wanted to support EML or EOTP, we would fail with a "Passwords not enabled" error.
- Yes, if passwords are disabled in the dashboard, but passed in as an option in the config it will still fail; this is intentional and makes sense.
> SDK-2348 only search users if passwords enabled

- gradle/libs.versions.toml
- source/sdk/src/main/java/com/stytch/sdk/common/dfp/DFPProvider.kt
- workbench-apps/b2b-workbench/build.gradle.kts
- workbench-apps/consumer-workbench/build.gradle.kts
Linear Ticket: [SDK-2379](https://linear.app/stytch/issue/SDK-2379)
1. Fixes reported webview leak in DFPProvider
2. Adds leakcanary to workbench apps for verification (and alerting us to future issues!)
- This leak (I believe) only happens in multiactivity workflows, and I was able to reproduce/fix/validate in the b2b workbench
> Fix leaking webview in DFPProvider

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/EmailConfirmationScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/PasswordForgotScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseSendCorrectPasswordReset.kt
1. Add the same "does member have a password?" check from PasswordForgot flow to EmailConfirmation resend flow
2. Unify it all in one reusable usecase
-
> B2B UI: Add member/non-member distinction in email confirmation screen resend method

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/StytchB2BProductConfig.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/DiscoveryScreen.kt
- workbench-apps/b2b-workbench/src/main/java/com/stytch/exampleapp/b2b/UIWorkbenchActivity.kt
Linear Ticket: [SDK-2382](https://linear.app/stytch/issue/SDK-2382)
1. Adds support for directOrgCreationOnZeroMemberships configuration option, for parity with JS SDK
-
> SDK-2382 direct org creation on zero memberships

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/Enums.kt
1. As titled
2. Bump patch version
-
> Add ALL_ALLOWED as a potential option for EmailJitProvisioning and OAuthTenantJitProvisioning

- source/sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIError.kt
- source/sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIErrorType.kt
- source/sdk/src/main/java/com/stytch/sdk/common/extensions/HttpExceptionExt.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/screens/ReturningUserScreenViewModel.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/oauth/OAuthImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/common/errors/StytchErrorTests.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/biometrics/BiometricsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/oauth/OAuthImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/ui/b2c/screens/MainScreenViewModelTest.kt
- source/sdk/src/test/java/com/stytch/sdk/ui/b2c/screens/ReturningUserScreenViewModelTest.kt
Linear Ticket: [SDK-2418](https://linear.app/stytch/issue/SDK-2418)
1. Updates all places that were using/expecting a string for API error types to use the new explicit enums
-
> SDK-2418 Use new explicit StytchAPIErrorType enum

- source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
Linear Ticket: [SDK-2390](https://linear.app/stytch/issue/SDK-2390)
1. Persists the passed options to enable short-circuiting
2. Short circuits if configure is called with the same public token and options
3. Adds tests for the above behavior
-
> SDK-2390 Prevent duplicate configure calls

- gradle/libs.versions.toml
- source/sdk/build.gradle.kts
- source/sdk/src/main/AndroidManifest.xml
- source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- source/sdk/src/main/java/com/stytch/sdk/common/AppLifecycleListener.kt
- source/sdk/src/main/java/com/stytch/sdk/common/NetworkChangeListener.kt
- source/sdk/src/main/java/com/stytch/sdk/common/dfp/CaptchaProvider.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
Linear Ticket: [SDK-2113](https://linear.app/stytch/issue/SDK-2113)
1. Adds listeners to refresh bootstrap (and DFP/CAPTCHA settings) when a device returns from being offline OR from being backgrounded
2. Use a WeakReference to the application context in callbacks to avoid potential memory leaks
3. Fix (potential) bug in instantiating a CAPTCHA client with an empty siteKey
- Tested on device and simulator
> SDK-2113 Refresh bootstrap data when network comes online or app returns from background

- source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
Linear Ticket: [SDK-2436](https://linear.app/stytch/issue/SDK-2436)
1. For B2B: add a guardrail to only refresh bootstrap data if the network is online
2. For B2B and B2C: fallback to the _previous_ bootstrap data in case of a failed request, to prevent overwriting a potentially good bootstrap response with a default one (we set it to default on init, so there will always be _something_ to fallback to)
- Imagine a scenario where a user is online and has a valid bootstrap response, goes offline (or backgrounds the app), comes back online (or foregrounds the app), and the bootstrap response fails for some reason (transient network issue). Previously we would set the bootstrap data to the _default_ response; now, we will set it to the _previous_ response (which is either the default response …
> SDK-2436 Ensure bootstrap data isn't overwritten from a failed network request

- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/ProductComponent.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/StytchB2BProductConfig.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/extensions/GenerateProductComponentsOrdering.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/MainScreen.kt
- source/sdk/src/test/java/com/stytch/sdk/ui/b2b/extensions/GenerateProductComponentsOrderingTest.kt
Linear Ticket: [SDK-2372](https://linear.app/stytch/issue/SDK-2372)
1. Updates product component ordering in pre-built B2B UI to match updated logic, specifically keeping OAuth and SSO buttons together, and adding dividers where appropriate
2. Adds tests to ensure the logic is correct
-
> SDK-2372 Update B2B UI component ordering

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
1. Remove the network sanity check when refreshing bootstrap data. Since we standardized on an "off by default" value, it was possible that the network didn't report it's status before the initial bootstrap call, and thus calls _before_ it did so would use incorrect bootstrap data.
-
> Remove network check from bootstrapping calls to prevent startup race condition

- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/screens/MainScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/screens/MainScreenViewModel.kt
- source/sdk/src/test/java/com/stytch/sdk/ui/b2c/screens/MainScreenViewModelTest.kt
Linear Ticket: [SDK-2447](https://linear.app/stytch/issue/SDK-2447)
1. Respect the order of components that were passed in in both the products list and OTP methods list
2. Moves the ordering into the viewmodel for testability
3. Adds tests of the above
-
> SDK-2447 Respect the order of components in B2C Prebuilt UI

- .github/workflows/autopublish.yml
- .github/workflows/publish.yml
- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/common/errors/StytchSDKError.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/biometrics/BiometricsImpl.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/biometrics/BiometricsImplTest.kt
Linear Ticket: [SDK-2471](https://linear.app/stytch/issue/SDK-2471)
1. To prevent issues with creating orphaned registrations or errors when attempting to delete a remote registration without being "fully" authenticated, instead prevent the creation of duplicate registrations on device.
2. Bump version
3. Update tests
4. Chore: copy the publishing steps from the "manual" publish workflow into the auto publish workflow, since just linking to it with the `uses` directive was never working
- This mimics whats now done in ReactNative and iOS SDKs
> SDK-2471 Reject attempted duplicate biometric registrations

- source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/extensions/OrganizationDataExt.kt
Linear Ticket: [SDK-2465](https://linear.app/stytch/issue/SDK-2465)
1. Mirrors changes made in: https://github.com/stytchauth/api/pull/6888.
2. Mirrors changes made in: https://github.com/stytchauth/stytch-ios/pull/404
- This is basically a no-op on Android, as we're not using it in UI, but will keep us in alignment with iOS
> SDK-2465 Add organization_slug to InternalOrganizationData response object

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/components/ResendableOTP.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/EmailOTPEntryScreen.kt
Linear Ticket: [SDK-2473](https://linear.app/stytch/issue/SDK-2473)
1. Fixes UI issue where email OTPs were incorrectly identified as expiring in 2 minutes, instead of 10
2. Bumps version
-
> SDK-2473 EOTP expires in 10 minutes, not 2

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/consumer/ConsumerAuthMethod.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/oauth/GoogleOneTapImpl.kt
Linear Ticket: [SDK-2487](https://linear.app/stytch/issue/SDK-2487/add-distinct-lastauthmethod-for-google-onetap)
1. Adds a distinct value for Google OneTap/CM, to distinguish between it and traditional OAuth, when persisting the last used auth method
-
> Add a distinct value for Google OneTap/CredentialManager

- .github/workflows/runOnGithub.yml
- build.gradle.kts
- source/sdk/build.gradle.kts
Linear Ticket: [SDK-755](https://linear.app/stytch/issue/SDK-755)
1. Add and configure JaCoCo
2. Add new workflow step to our default PR workflow to comment with code coverage results
- Need to fine tune the exclusions. We don't need to have code coverage of every `data class`, for instance
- Need to fine tune the pass/fail metrics once we have a good (relevant) baseline
> Attempt to get code coverage reports in PRs

- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/utils/B2BUIViewModelFactory.kt
Linear Ticket: [SDK-2512](https://linear.app/stytch/issue/SDK-2512)
1. Remove the need to explicitly set each viewmodel in the factory. We can rely on the constructor method signatures to get the appropriate constructor.
- This will make it easier to add new viewmodels going forward, and removes the warnings about unchecked casts
> SDK-2512 Simplify viewmodelfactory and remove unchecked casts

- source/sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessions.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionsImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/sessions/Sessions.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/sessions/SessionsImpl.kt
Linear Ticket: [SDK-2510](https://linear.app/stytch/issue/SDK-2510)
1. Make sessionJwt optional when calling updateSession
- Companion to https://github.com/stytchauth/stytch-ios/pull/423
> SDK-2510 Make sessionJWT optional in updatesession methods

- source/sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionsImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/common/errors/StytchAPIError.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/ApiService.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/sessions/SessionsImpl.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiServiceTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/sessions/B2BSessionsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiServiceTests.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/sessions/SessionsImplTest.kt
Linear Ticket: [SDK-2583](https://linear.app/stytch/issue/SDK-2583)
1. Stop revoking sessions on all 401 errors. Instead, follow the JS model of only revoking if a revoke call succeeds OR a revoke call fails and `forceClear == true` OR an authenticate call fails with an unrecoverable error type
2. Add tests for new behavior
-
> SDK-2583 Limit scope of automatic session revocation to sessions authenticate/revoke calls, and only for certain conditions

- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/main/MainScreenViewModel.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseSendCorrectPasswordReset.kt
We were deciding how to handle password reset flows (specifically, whether to use a "non member" flow) based not just on whether a member exists, but also on whether the member has a password. Instead, only consider whether the member exists, regardless of whether they have a password.
Linear Ticket: [SDK-2588](https://linear.app/stytch/issue/SDK-2588)
1. Only check the existence of a member, instead of the existence of a member password
- Same change as JS SDK made: https://github.com/stytchauth/js-sdk-turbo/pull/1635
> SDK-2588 - Fix JIT provisioning bug in B2B UI

- source/sdk/src/main/java/com/stytch/sdk/b2b/Typealiases.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sso/SSO.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sso/SSOImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UseSSODiscoveryConnections.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/sso/SSOImplTest.kt
Linear Ticket: [SDK-2597](https://linear.app/stytch/issue/SDK-2597)
1. Expose SSO Discover Connections on the Headless client
2. Update the UI client to use that, instead of the internal endpoint
-
> SDK-2597 Expose SSO Discover Connections on the Headless client

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- source/sdk/src/main/java/com/stytch/sdk/common/ConfigurationManager.kt
- source/sdk/src/main/java/com/stytch/sdk/common/dfp/DFPConfiguration.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/ApiService.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/CommonApi.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/StytchDFPInterceptor.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- source/sdk/src/test/java/com/stytch/sdk/common/network/StytchDFPInterceptorTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
1. Instead of adding/removing interceptors when the bootstrap changes, only add them once, and change their _configuration_ when that changes.
-
> Better handling of Interceptors

- source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- source/sdk/src/main/java/com/stytch/sdk/common/ConfigurationManager.kt
- source/sdk/src/main/java/com/stytch/sdk/common/StytchClientCommon.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/data/B2BPasswordOptions.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UsePasswordDiscoveryResetByEmailStart.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/usecases/UsePasswordResetByEmailStart.kt
Linear Ticket:
[SDK-2611](https://linear.app/stytch/issue/SDK-2611)
[SDK-2613](https://linear.app/stytch/issue/SDK-2613)
1. Add resetPasswordExpirationMinutes to B2B UI config passwordoptions and pass to underlying client methods where appropriate
2. Add vertical to bootstrapdata and add logging when misconfigured
-
> Add missing properties to BootstrapData and B2B UI PasswordOptions

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/b2b/extensions/StytchResultExt.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- source/sdk/src/main/java/com/stytch/sdk/common/ConfigurationManager.kt
- source/sdk/src/main/java/com/stytch/sdk/common/StorageHelper.kt
- source/sdk/src/main/java/com/stytch/sdk/common/dfp/DFPProvider.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/ThreadingInterceptor.kt
- source/sdk/src/main/java/com/stytch/sdk/common/sessions/SessionAutoUpdater.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/extensions/StytchResultExt.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- workbench-apps/consumer-workbench/src/main/java/com/stytch/exampleapp/App.kt
Linear Ticket: [SDK-2646](https://linear.app/stytch/issue/SDK-2646)
1. Enables strict mode in the demo app to try and track down any potential violations that might cause ANRs. Everything that was reported has been fixed, except some initialization stuff deep in the heart of reCAPTCHA that we have no control over
2. Fix a bug where we weren't clearing sessions on a failed heartbeat
-
> SDK-2646 address StrictMode violations and fix session revocation on heartbeat

- source/sdk/build.gradle.kts
- source/sdk/src/main/AndroidManifest.xml
- source/sdk/src/main/java/com/stytch/sdk/common/EncryptionManager.kt
- source/sdk/src/main/java/com/stytch/sdk/common/StorageHelper.kt
- source/sdk/src/main/java/com/stytch/sdk/common/extensions/ContextExt.kt
- source/sdk/src/main/res/xml/android_11_and_lower_backup_rules.xml
- source/sdk/src/main/res/xml/android_12_and_higher_backup_rules.xml
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/magicLinks/B2BMagicLinksImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/member/MemberImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/oauth/OAuthImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/organization/OrganizationImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/passwords/PasswordsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/rbac/RBACImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/sessions/B2BSessionsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/sso/SSOImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/common/pkcePairManager/PKCEPairManagerImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/biometrics/BiometricsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/magicLinks/MagicLinksImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/oauth/OAuthImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/otp/OTPImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/passwords/PasswordsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/sessions/SessionsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/userManagement/UserManagementImplTest.kt
Linear Ticket: [SDK-2640](https://linear.app/stytch/issue/SDK-2640)
1. We persist our encryption key data to a shared preferences file that, by default, is backed up and restored when reinstalling an application. However, the key that that data points to is _not_ persisted between installs (enforced by Android; working as expected). So when we allow our data to be persisted, it means that first launches of an app after reinstall attempt to use an invalid key, and fail to decrypt the data. This change is to explicitly disallow backing up our preference files, preventing the app from attempting to use an invalid key. In the event that data was previously persisted (ie: someone had an older version installed, then uninstalled the app, and reinstalled with an app using _this_ version), …
> SDK-2640 Add backup/extraction rules

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/StytchB2BAuthenticationApp.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/discovery/DiscoveryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/smsOTPEntry/SMSOTPEntryScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/smsOTPEntry/SMSOTPEntryScreenViewModel.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/totpEnrollment/TOTPEnrollmentScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2b/screens/totpEnrollment/TOTPEnrollmentScreenViewModel.kt
Linear Ticket: [SDK-2666](https://linear.app/stytch/issue/SDK-2666)
1. Fix overflowing long organization names in discovery screen and ensure the logo is scaled to fill
2. Noticed some VM recreation and ensured VMs are only created once. As a caveat of that, there were some places we were relying on the initialization behavior that we now need to explicitly call on screen load (NB: this means that these inits were running multiple times previously, which could potentially cause issues with triggering multiple TOTP or SMS events)
-
> SDK-2666 Minor B2B UI Fixes

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/AuthenticationActivity.kt
Detected a potential memory leak in B2C prebuilt UI if launched multiple times. Instead of using the callback form for listening to user changes, instead collect changes with lifecycle awareness.
> Fix B2C UI memory leak

- example-apps/stytchexampleapp/src/main/java/com/stytch/stytchexampleapp/MainActivity.kt
- example-apps/stytchexampleapp/src/main/java/com/stytch/stytchexampleapp/MainViewModel.kt
- example-apps/stytchexampleapp/src/main/java/com/stytch/stytchexampleapp/Route.kt
- example-apps/stytchexampleapp/src/main/java/com/stytch/stytchexampleapp/ui/screens/login/LoginRoute.kt
- example-apps/stytchexampleapp/src/main/java/com/stytch/stytchexampleapp/ui/screens/profile/ProfileRoute.kt
- source/sdk/build.gradle.kts
- source/sdk/src/androidTest/java/com/stytch/sdk/ui/b2c/BaseAndroidComposeTest.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/AuthenticationActivity.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/AuthenticationViewModel.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/data/ApplicationUIState.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/data/BiometricsOptions.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/data/StytchProduct.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/data/StytchProductConfig.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/screens/BiometricRegistrationScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/screens/BiometricRegistrationScreenViewModel.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/screens/MainScreen.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/screens/MainScreenViewModel.kt
- source/sdk/src/main/java/com/stytch/sdk/ui/shared/components/SocialLoginButton.kt
- source/sdk/src/main/res/values/strings.xml
- source/sdk/src/test/java/com/stytch/sdk/ui/b2c/screens/MainScreenViewModelTest.kt
Linear Ticket: [SDK-2681](https://linear.app/stytch/issue/SDK-2681)
1. Add support to the consumer prebuilt UI for biometrics registration and authentication.
2. You can configure it so that you do or do not register after authentication via the `BiometricsOptions`.
3. If you choose not to register via the prebuilt UI you will have to call register from elsewhere.
4. In either case if the user is somehow registered and you include in the product config `StytchProduct.Biometrics` then a button will be added to the home screen to authenticate with biometrics.
-
> Add Biometrics To The Consumer Prebuilt UI

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/b2b/network/StytchB2BApi.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/oauth/OAuthImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sso/SSOImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/common/ConfigurationManager.kt
- source/sdk/src/main/java/com/stytch/sdk/common/Constants.kt
- source/sdk/src/main/java/com/stytch/sdk/common/EndpointOptions.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/CommonApi.kt
- source/sdk/src/main/java/com/stytch/sdk/common/utils/GetApiUrl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/oauth/ThirdPartyOAuthImpl.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/network/StytchB2BApiTest.kt
- source/sdk/src/test/java/com/stytch/sdk/common/utils/GetApiUrlTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/network/StytchApiTest.kt
Linear Ticket: [SDK-2688](https://linear.app/stytch/issue/SDK-2688)
1. Adds support for custom domains
2. Adds CNAME checking to B2B OAuth where it was missing
-
> SDK-2688 Support custom API domains

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/ui/b2c/screens/MainScreenViewModel.kt
Linear Ticket: [SDK-2718](https://linear.app/stytch/issue/SDK-2718)
1. Adds a failure check to Google Credential Manager (OneTap) flow in PreBuilt B2C UI to fallback to regular OAuth if it fails for some reason
2. Fixes an issue where the loading spinner doesn't disappear on a canceled/failed OAuth flow
-
> SDK-2718 Fallback to regular Google OAuth if CredentialManager fails

- source/sdk/build.gradle.kts
- source/sdk/src/main/assets/dfp.html
- source/sdk/src/main/java/com/stytch/sdk/common/ConfigurationManager.kt
- source/sdk/src/main/java/com/stytch/sdk/common/StytchClientOptions.kt
- source/sdk/src/main/java/com/stytch/sdk/common/dfp/DFPProvider.kt
- source/sdk/src/main/java/com/stytch/sdk/common/dfp/DFPType.kt
- source/sdk/src/main/java/com/stytch/sdk/common/dfp/WebviewActivityProvider.kt
Linear Ticket: [SDK-2719](https://linear.app/stytch/issue/SDK-2719)
1. Adds a new option to `StytchClientOptions` to switch between native and webview DFP implementations
2. Updates `DFPProvider` to instantiate and use the correct DFP implementation based on configuration
- To use webview DFP, one would need to pass the following to `StytchClient.configure()`: `StytchClientOptions(dfpType = DFPType.Webview)`
> SDK-2719 Add configuration option to choose between webview and native DFP implementations

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/member/MemberImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/organization/OrganizationImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionStorage.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionsImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/common/ConfigurationManager.kt
- source/sdk/src/main/java/com/stytch/sdk/common/StorageHelper.kt
- source/sdk/src/main/java/com/stytch/sdk/common/StytchObjectInfo.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/sessions/ConsumerSessionStorage.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/sessions/SessionsImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/userManagement/UserManagementImpl.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/common/pkcePairManager/PKCEPairManagerImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
Linear Ticket: No ticket
1. Return the job created when instantiating the StorageHelper so that we can wait for it to complete before trying to access persisted data
2. Don't emit values from persisted data until after everything is loaded
3. Introduce a new default "Loading" state to prevent publishing `Unavailable` when what we really mean is "we don't know yet"
-
> Startup race condition

- gradle/libs.versions.toml
- source/sdk/build.gradle.kts
Linear Ticket: [SDK-2780](https://linear.app/stytch/issue/SDK-2780)
1. Bump DFP version to 16kb supporting version
- https://android-developers.googleblog.com/2025/05/prepare-play-apps-for-devices-with-16kb-page-size.html
> SDK-2780 Bump dfp to support 16kb page sizes

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/b2b/extensions/StytchResultExt.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionsImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/common/sessions/SessionAutoUpdater.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/extensions/StytchResultExt.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/sessions/SessionsImpl.kt
Linear Ticket: No ticket
1. Same as https://github.com/stytchauth/stytch-ios/pull/513, except for the unnecessary error propagation
-
> Adopt guardrails around session storms

- source/sdk/src/main/java/com/stytch/sdk/b2b/network/models/B2BResponseData.kt
- source/sdk/src/main/java/com/stytch/sdk/common/network/models/CommonResponseData.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/Typealiases.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/crypto/CryptoWallet.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/crypto/CryptoWalletImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApi.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/StytchApiService.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/models/ConsumerResponses.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/network/models/ResponseData.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/otp/OTP.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/otp/OTPImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/passkeys/Passkeys.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/passkeys/PasskeysImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/passwords/Passwords.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/passwords/PasswordsImpl.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/crypto/CryptoWalletImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/otp/OTPImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/passkeys/PasskeysImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/passwords/PasswordsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/ui/b2c/screens/OTPConfirmationScreenViewModelTest.kt
- source/sdk/src/test/java/com/stytch/sdk/ui/b2c/screens/ReturningUserScreenViewModelTest.kt
- source/sdk/src/test/java/com/stytch/sdk/ui/b2c/screens/SetPasswordScreenViewModelTest.kt
Linear Ticket: [SDK-2822](https://linear.app/stytch/issue/SDK-2822)
1. Adds user/member device history per JS/RN implementation
- Annoyingly, a lot of the B2C auth endpoints were using a shared `AuthData` response, so needed to create custom response types for these instances.
> SDK-2822 Add user/member device history

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/common/ConfigurationManager.kt
1. Trigger a session validation check when the network or lifecycle changes to ensure stale tokens are not persisted when a session expires while backgrounded
-
> Do session hydration checking on lifecycle changes

- CODEOWNERS
- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/common/Constants.kt
- source/sdk/src/main/java/com/stytch/sdk/common/StorageHelper.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/biometrics/BiometricsImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/biometrics/BiometricsProvider.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/biometrics/BiometricsProviderImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/extensions/UserDataExt.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/sessions/ConsumerSessionStorage.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/biometrics/BiometricsImplTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/extensions/UserDataExtTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/sessions/ConsumerSessionStorageTest.kt
Linear Ticket: [SDK-2816](https://linear.app/stytch/issue/SDK-2816)
1. Keep track of the last authenticated user, and when the user changes, clean up biometric registrations as appropriate. If there was no previous user, or the previous user and current user are the same, just clean up any potentially device-orphaned registrations (existing behavior). If a _new_ user is logged in, remove any existing biometric registrations to enable the new user to create their own. This creates a server-orphaned registration but new changes in the API will handle these as necessary.
-
> SDK-2816 biometrics registration management

- source/sdk/src/main/java/com/stytch/sdk/b2b/StytchB2BClient.kt
- source/sdk/src/main/java/com/stytch/sdk/b2b/extensions/StytchResultExt.kt
- source/sdk/src/main/java/com/stytch/sdk/common/StytchClientOptions.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/StytchClient.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/extensions/StytchResultExt.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
Linear Ticket: [SDK-2901](https://linear.app/stytch/issue/SDK-2901)
1. Instead of just validating a session during the heartbeat, also attempt to _extend_ the session duration by the default session length
-
> SDK-2901 auto extend session

- source/sdk/build.gradle.kts
- source/sdk/src/main/java/com/stytch/sdk/b2b/sessions/B2BSessionStorage.kt
- source/sdk/src/main/java/com/stytch/sdk/common/events/EventsImpl.kt
- source/sdk/src/main/java/com/stytch/sdk/common/utils/DateHelpers.kt
- source/sdk/src/main/java/com/stytch/sdk/consumer/sessions/ConsumerSessionStorage.kt
- source/sdk/src/test/java/com/stytch/sdk/b2b/StytchB2BClientTest.kt
- source/sdk/src/test/java/com/stytch/sdk/consumer/StytchClientTest.kt
Linear Ticket: [SDK-2903](https://linear.app/stytch/issue/SDK-2903)
1. Since `SimpleDateFormat` is not thread safe, introduce a hashmap of `ThreadLocal` instances. This ensures calls to format/parse dates are thread safe while also avoiding expensive reinitialization of everything that SDF implements under the hood for functionality (calendars and the like)
- Ideally, we would use `java.time.*` implementations and this would be a lot simpler, but those aren't available until SDK 26, and we support down to 23. We _could_ use core desugaring to get access to those in earlier SDKs, but it requires our customers to _also_ opt-in to that, and I'm trying to fix this with 0 customer effort
- Closes #374
> SDK-2903 Fix SimpleDateFormat crash

- .github/workflows/dependency-submission.yml
1. Updates dependency submission workflow to only look at SDK dependencies
-
> Ensure dependencies/dependabot is only looking at the core SDK dependencies
